name: First messed up Git Actions


on:
 push:
  branches: [ main ]
 schedule:
    - cron: "30 5,17 * * *"

 workflow_dispatch:


jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: running messed code
      run:  echo let us hope it works

