name: First time Writing cool Git Actions

run-name: Actions for testActions

on:
 push:
  branches: [ main ]
 schedule:
    - cron: "30 5,17 * * *"

 workflow_dispatch:


jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: action/checkout@v3
    - name: running multiple commands
      run:|
        echo First Command
        echo Second Command







 test-schedule:
   runs-on: ubuntu-latest
   name: Node setup
   steps:
     - name: First Action
       run: echo ok ready to run
     - uses: action/checkout@v3
     - uses: action/setup-node@v3
       with:
          node-version: '16'
     -name: Running a node stuff,..
      run: npm install jade -g
     -run: jade -V
